### ISSUE TITLE
rust_winit> error: Please select a feature to build for unix: `x11`, `wayland`

### ISSUE THREAD

**Issue by magnetophon** [vizia/vizia#193]
When I try to build [https://github.com/magnetophon/vizia-audio-synth](https://github.com/magnetophon/vizia-audio-synth), which is basically the first step of https://github.com/geom3trik/vizia-audio-synth, I get the error in the title.

I'm building using nix, with the command:
```
nix build -L -f Cargo.nix workspaceMembers.audio_synth.build
``` 

After a helpful chat with @geom3trik he told me to make an issue for it.

**Comment by KDecay** [comment]
Not sure what exactly the problem on your end is, but I usually use a `nix-shell` with the `shell.nix` seen below. It is by no means a minimal `shell.nix` to compile it but it's what I use for all of my Rust projects.

I tried to compile your fork of the `vizia-audio-synth`. It didn't work initially with your fork of `vizia` so I switched it from:
`vizia = {git = "https://github.com/magnetophon/vizia", features = ["x11"]}`
to:
`vizia = {git = "https://github.com/vizia/vizia", features = ["x11"]}`
which at least let me compile it without any problems.

```nix
let
  moz_overlay = import (builtins.fetchTarball
    "https://github.com/mozilla/nixpkgs-mozilla/archive/master.tar.gz");
  nixpkgs = import <nixpkgs> { overlays = [ moz_overlay ]; };
in with nixpkgs;
stdenv.mkDerivation {
  name = "moz_overlay_shell";
  nativeBuildInputs = [ pkgconfig clang lld ];
  buildInputs = [
    (nixpkgs.rustChannelOf { date = "2022-07-02"; channel = "nightly"; }).rust
    rustup
    pkgconfig
    openssl
    xorg.libxcb
    xlibsWrapper

    glib
    atk
    cairo
    gdk-pixbuf
    pango
    gtk3

    udev
    alsaLib
    alsa-lib
    vulkan-loader
    libGL
    egl-wayland
    xorg.libXcursor
    xorg.libXrandr
    xorg.libXi
    libxkbcommon
  ];
  shellHook = ''
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${
      pkgs.lib.makeLibraryPath [ udev alsaLib vulkan-loader libGL libxkbcommon ]
    }"'';
}
```

**Comment by KDecay** [comment]
I now tried your solution with the following command:
```
nix build -L -f Cargo.nix workspaceMembers.audio_synth.build
```

I was able to reproduce your issue and got a little further by adding `features = [ "x11" ]` to two of the `winit` dependencies in the `Cargo.nix` file. `winit` is a dependency of `glutin` and also `vizia_winit`.

Now I don't get the `Please select a feature to build for unix` error anymore but now I get `Builder called die: Cannot wrap '/nix/store/f9ns7a1d63pb27ccbdqjh4x2bfbarnaa-rust_winit-0.27.1/bin/winit' because it is not an executable file`. Not quite how to fix that one though.

**Comment by magnetophon** [comment]
@KDecay Thanks a lot for your reply!

Adding the two instances of ``features`` has the same effect here: it compiles fine, but complains about the ``postInstall`` (which I got [here](https://github.com/Anton-4/winit_nix/blob/ffebf8f39dcab976e486671cb25ebb593befac20/flake.nix#L41).

What I found really strange:
- ``/nix/store/58fly8hz33al8b04nwwlysh8i5hnz3fb-rust_winit-0.27.1/``, where the ``postInstall`` error pointed me, is an empty directory
- When I comment out [those lines](https://github.com/magnetophon/vizia-audio-synth/blob/master/Cargo.nix#L7277-L7279), I get  ``Please select a feature to build for unix`` again!

**Comment by magnetophon** [comment]
I'm now running ``nix-shell shell.nix``, using your ``shell.nix``, followed by ``cargo run``.
Is that how you did it?

**Comment by KDecay** [comment]
> I'm now running nix-shell shell.nix, using your shell.nix, followed by cargo run.
Is that how you did it?

Yup, the exact process is as follows:
1. Create the `shell.nix` (preferably in the project directory).
2. `cd` into the directory of the `shell.nix` file.
3. Run `nix-shell`.
4. `cd` into the project directory if you aren't there already.
5. Run `cargo run`.

**Comment by magnetophon** [comment]
@KDecay Thanks!

When I use the upstream vizia, it builds and runs!

I'd like to get the Cargo.nix working too, as that lets me build remotely, but this at least shows it's a ``nix`` or ``crate2nix`` issue and not a ``vizia`` one.

**Comment by KDecay** [comment]
> @KDecay Thanks a lot for your reply!

No worries!

> Adding the two instances of features has the same effect here: it compiles fine, but complains about the postInstall (which I got [here](https://github.com/Anton-4/winit_nix/blob/ffebf8f39dcab976e486671cb25ebb593befac20/flake.nix#L41).

It seems to wrap the wrong thing here. The error message states that it expects a executable file, but `winit` is a library. What's the reason you added this?

> What I found really strange:
    /nix/store/58fly8hz33al8b04nwwlysh8i5hnz3fb-rust_winit-0.27.1/, where the postInstall error pointed me, is an empty directory
    When I comment out [those lines](https://github.com/magnetophon/vizia-audio-synth/blob/master/Cargo.nix?rgh-link-date=2022-08-09T19%3A37%3A18Z#L7277-L7279), I get Please select a feature to build for unix again!

Huh interesting. Not sure how libraries get stored in the `nix/store`. It's complaining about not finding an executable in `bin/winit` which makes sense since it's not an executable. I wonder why you get the error again though.

**Comment by KDecay** [comment]
> When I use the upstream vizia, it builds and runs!

Awesome! Happy to help :)

> I'd like to get the Cargo.nix working too, as that lets me build remotely, but this at least shows it's a nix or crate2nix issue and not a vizia one.

Understandable. Let us know if you get it working!

**Comment by magnetophon** [comment]
> What's the reason you added this?

When I found an example to take the buildInputs from, I just copied it along, see link above.

>  Not sure how libraries get stored in the nix/store

``/nix/store/58fly8hz33al8b04nwwlysh8i5hnz3fb-rust_winit-0.27.1/`` is the ``$out`` of  ``winit``, the place where ``winit`` should be stored. There is nothing there, which I find odd. 
I am new to rust, but for other libraries, $out would contain a ``lib`` dir, or at least something!

**Comment by KDecay** [comment]
> When I found an example to take the buildInputs from, I just copied it along, see link above.

I see. Might be a good idea to ask on the nix discord if they can explain what it does or what it is used for.

> /nix/store/58fly8hz33al8b04nwwlysh8i5hnz3fb-rust_winit-0.27.1/ is the $out of winit, the place where winit should be stored. There is nothing there, which I find odd.
I am new to rust, but for other libraries, $out would contain a lib dir, or at least something!

Makes sense. I would expect something similar, but I never really look into the `nix/store` tbh ^^ It being empty is really weird though. Might also be worth asking the folks over at the nix discord. They have a dedicated `#rust` channel there.

Here is the link to their discord if you aren't part of it yet:
https://discord.com/invite/RbvHtGa

**Comment by magnetophon** [comment]
@KDecay Thanks, I was  already on the nix discord, and asked the question just now.
Are you also there?
What's your nick?

**Comment by KDecay** [comment]
@magnetophon Yup, I'm also there.
My discord is `KDecay#9324`.
