### ISSUE TITLE
Textbox focus leads to unintuitive blur behavior

### ISSUE THREAD

**Issue by rhelmot** [vizia/vizia#211]
- Have a textbox and a button
- Click on the textbox to focus
- Click on the button
- The textbox blurs but the button doesn't press and you have to click again to activate it

**Comment by 0HyperCube** [comment]
The textbox was capturing events, so when you click outside of the textbox it deactivated and sent another MouseDown, however the button is now using TriggerDown so that has to be forwarded as well. Done in #209

**Comment by geom3trik** [comment]
Fixed by #209
