### ISSUE TITLE
Introduce `Press` and `PressDown` events

### ISSUE THREAD

**Issue by geom3trik** [vizia/vizia#233]
I would like to introduce a `WindowEvent::Press` event which would trigger when a view has been pressed, i.e. the primary mouse button is pressed down and then released on the view, or the trigger key (space, enter) is pressed and then released on a view.

I would then like to rename `TriggerDown` to `PressDown`. So `Press` would be for a down then up action on the view and `PressDown` would be for a down action on the view.

**Comment by iwoithe** [comment]
It would be nice to also add a ``PressUp`` event which would be for when an action (mouse press, trigger keys etc.) is released on the view.

**Comment by geom3trik** [comment]
> It would be nice to also add a ``PressUp`` event which would be for when an action (mouse press, trigger keys etc.) is released on the view.

We could do, and I did initially think of that too, but I can't think of an actual use for this. `Press` is for when the view is pressed down and also released, `PressDown` is for when the view is just pressed down, but `PressUp` would be for when some other view is pressed down but released on the view in question. This could be possible for a mouse button, but I don't see how it's possible (or useful) for a keyboard key. In which case this is already covered by the `MouseUp` event.
