### ISSUE TITLE
Image example panics with baseview backend

### ISSUE THREAD

**Issue by geom3trik** [vizia/vizia#283]
Panics with the following message:
```
thread 'main' panicked at 'expected non-zero GL name', C:\Users\geomy\.cargo\registry\src\github.com-1ecc6299db9ec823\glow-0.11.2\src\native.rs:96:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by PieKing1215** [comment]
Don't mean to pressure you but is there any chance the fix for this will merge any time soon?
I would need this eventually for a project and I'm trying to figure out if using Vizia is feasible.

**Comment by geom3trik** [comment]
> Don't mean to pressure you but is there any chance the fix for this will merge any time soon?
> I would need this eventually for a project and I'm trying to figure out if using Vizia is feasible.

The fix is currently part of an upcoming PR but I can cherrypick it for main if you need it soon. Are you using nih-plug though?

**Comment by PieKing1215** [comment]
> Are you using nih-plug though?

Yep, as far as I could tell it seems like on nih-plug's master Vizia and Iced both don't have working image support which would mean I'd have to use egui which is definitely not the ideal choice for my project.

**Comment by geom3trik** [comment]
I can patch vizia to fix the problem but it may take a little while for the change to make its way to nih-plug.

**Comment by PieKing1215** [comment]
Sure, if it's not too much trouble that'd be great.
It's not super urgent, I was just figuring it would take much longer if nih-plug also needed to wait for #291.
