### ISSUE TITLE
Other Text-related features

### ISSUE THREAD

**Issue by LunaeSomnia** [vizia/vizia#294]
Currently, there are very little text-related styling properties to be applied in Vizia. These are some other properties that would be great to have:

- [ ] Line Height
- [ ] Letter Spacing
- [ ] Letter Casing (Auto change to UPPERCASE, lowercase, and others)
- [ ] Rich text
- [ ] Paragraph spacing
- [ ] Paragraph indentation

Edit:
- [ ] Text decoration (Underlines, squiggles and strikethrough)

**Comment by geom3trik** [comment]
We can borrow from css for letter spacing which is just an additional space between letters.

Can I also add strikethrough to the list? Potentially with its own color as well perhaps?

**Comment by LunaeSomnia** [comment]
> I'm not sure what the interface for letter spacing should look like. Maybe the easiest would be number of additional pixels between glyphs?

This is often used by percentages... but yeah I guess it can be transposed to pixels

I'm updating the list with your comments
