### ISSUE TITLE
Scrollview has bad visibility check

### ISSUE THREAD

**Issue by DasLixou** [vizia/vizia#306]
When playing around with scrollview to understand it and later try to implement #74 , i stumbled across an issue:
The visibility is only checked by the top left corner (at least thats what i think)
Example:
At the top:
![image](https://user-images.githubusercontent.com/82600264/218731392-3d4a9dda-0f63-4399-8001-53ced59ebf1d.png)
Then moving it just a little bit down and the green bar disappears:
![image](https://user-images.githubusercontent.com/82600264/218731495-bc405313-579a-4064-8d93-d840e8a9192f.png)

this is recognizable trough the whole `scrollview` example

---

3rd issue = 3rd times the charm 😅

**Comment by DasLixou** [comment]
This even gets worse at the bottom example:
![image](https://user-images.githubusercontent.com/82600264/218731942-84894dac-a337-445d-9cdd-74ac6a59a98a.png)
where it just overrenderes white
![image](https://user-images.githubusercontent.com/82600264/218731986-117446da-29cd-45d3-8e0b-09ae6210c11c.png)

**Comment by geom3trik** [comment]
Yep you are quite right. I accidentally introduced this bug but it's fixed in #302.

**Comment by DasLixou** [comment]
Oh Good! :D

**Comment by DasLixou** [comment]
Is this fixed now? I currently have no computer available to check, @geom3trik does the Scrollview example work now?

**Comment by geom3trik** [comment]
Yes, this is now fixed.
