### ISSUE TITLE
[Feedback Wanted] Proposal to remove the Model trait

### ISSUE THREAD

**Issue by geom3trik** [vizia/vizia#337]
Okay, so currently vizia enforces a separation between app state and UI views with two traits, `Model` and `View`. Typically you define some model data and mutate it in response to events like so:

```rust
#[derive(Lens)]
pub struct AppData {
    some_data: String,
}

impl Model for AppData {
    fn event(&mut self, cx: &mut EventContext, event: &mut Event) {
        // Respond to events and mutate model data here
    }
}
```

This model data then needs to be built into the app. Although it exists separately to views, the data is 'attached' to a view so that descendants can bind to the data and events can propagate to the model.

```rust
HStack::new(cx, |cx|{
    AppData { some_data: "Hello World".to_string() }.build(cx); // Model is 'attached' to the hstack in the tree
});
```

Although models can be built anywhere, the typical usage is to build one or more models at the root application level:

```rust
Application::new( |cx|{
    AppData { some_data: "Hello World".to_string() }.build(cx);

   // Build the rest of the UI here
});
```

Now views can also contain view-specific data and mutate that data in response to events. At some point we also made it possible to bind to this data by deriving `Lens` on the view struct:

```rust
#[derive(Lens)]
pub struct CustomView {
    some_data: String,
}

impl View for CustomView {
    fn event(&mut self, cx: &mut EventContext, event: &mut Event) {
        // Respond to events and mutate view data here
    }
}
```

The main difference here is how that data is 'built' into the app. Essentially it belongs to the view and the view is built into the app in the usual way:

```rust
CustomView::new(cx, |cx|{
    // Descendants of the view can bind to its data
});
```

At this point I'm sure you can see the duplication between a `Model` and a `View`. Now a `Model` does allow you to attach data to a view that doesn't typically have any (e.g. the HStack example above), but I think this could be replaced by a custom view which contains the data and behaves as a hstack.

The proposal then is to remove the `Model` trait and just have the `View` trait, with the binding and event handling functionality being the same.

However, this does present an issue when dealing with data that should be at the root application level. To allow for this, the application would need to become a trait which the user implements on their own struct:

```rust
pub struct App {
    some_app_data: AppData,
}

impl Application for App {
    fn event(&mut self, cx: &mut EventContext, event: &mut Event) {
        // Handle top-level events and mutate the application data
    }
}

fn main() {
    App::new(|cx|{
        // Build the UI here
    })
}
```

The downsides here are: 
- slightly more boilerplate to set up the initial application
- all the top level state needs to live in the app struct instead of the possibility of splitting it across multiple models. 

The upsides are: 
- less duplication
- a simpler interface for users, i.e. users only need to be concerned with views and it's clear where that data lives and when it gets updated.

Looking for opinions on this, particularly from anyone who is currently using vizia for a project.

**Comment by rhelmot** [comment]
I think the single most important consideration we need to make is how this is going to interact with future plans to optimize lens value recomputation. We've talked about trying to make the process of checking that bindings should be rebuilt more granular, since at present this interacts _extremely poorly_ with having all your data in a single root model/view. I'd like to talk about what that might look like before we go all in on this, since it removes the main possible avenue for mitigating this performance issue.

**Comment by geom3trik** [comment]
> I think the single most important consideration we need to make is how this is going to interact with future plans to optimize lens value recomputation. We've talked about trying to make the process of checking that bindings should be rebuilt more granular, since at present this interacts _extremely poorly_ with having all your data in a single root model/view. I'd like to talk about what that might look like before we go all in on this, since it removes the main possible avenue for mitigating this performance issue.

You make a very good point. I'm not convinced that there isn't a solution that allows for data to be in one (or very few) model(s) but you're right that perhaps we need to figure that out before moving anywhere on this idea. Though technically this change wouldn't force data to be in a single model, since the data could be spread out amongst several views.
