### ISSUE TITLE
Setting overflow: hidden on a parent with border-radius doesn't clip contents in the corners

### ISSUE THREAD

**Issue by Fredemus** [vizia/vizia#401]
Maybe a bug: setting `overflow: hidden` on an ``Hstack` with `border-radius: >0px` doesn't stop the stuff beyond the border radius from rendering
In the pic you can see the red border being behind whatever's in the `Hstack` at the corners. I made the Hstack too short for the contents to make the problem more obvious. 

![image](https://github.com/vizia/vizia/assets/46689307/6d627a28-3a16-4ab0-82bc-f21198e80c8c)

**Comment by geom3trik** [comment]
This is a limitation of femtovg unfortunately. I have an idea how this might be solvable, but I haven't had the time to put much development effort into it yet.

**Comment by Fredemus** [comment]
Ah fair enough. I figured out how to do border radius on custom views so it's not a high priority for me
