### ISSUE TITLE
on_press event bug: event fails to trigger when pressing children

### ISSUE THREAD

**Issue by Fredemus** [vizia/vizia#406]
If you run the following code and click on the rendered Hstack outside of the labels visible, both "ON PRESS" and "ON MOUSE DOWN" gets printed. However, if you click on the labels, only "ON MOUSE DOWN" gets printed.

```rust
use vizia::prelude::*;

const STYLE: &str = r#"
    .lfo-button {
        width: 1s;
        height: 17px;
        /* child-space: 5px; */
        background-color: #181818;
        /* border-width: 1px;
        border-color: #101010; */
        color: #ffffff80;
    }
"#;
fn main() {
    Application::new(|cx| {
        cx.add_stylesheet(STYLE).expect("Failed to add stylesheet");
        make_mod_source_button(cx, "LFO 1");
    })
    .run();
}
pub fn make_mod_source_button<'a>(cx: &'a mut Context, text: &'static str) -> Handle<'a, HStack> {
    // modulated_by is index to combined modulators for ui visualiztion, not what we need
    HStack::new(cx, |cx| {
        Label::new(cx, text).left(Pixels(4.));
        Label::new(cx, "1")
            .color(Color::from("#4DFF30"))
            .width(Auto)
            .right(Pixels(4.))
            .left(Stretch(1.));
    })
    .class("lfo-button")
    .on_mouse_down(move |cx, _| {
        println!("ON MOUSE DOWN");
    })
    .on_press(move |cx| {
        println!("ON PRESS");
    })
}
```

**Comment by geom3trik** [comment]
This behaviour was changed fairly recently but is now the expected behaviour. When hovering the labels the press event is not triggered for the hstack. The solution is to set the labels to `.hoverable(false)`, or you can use `pointer-events: none` in css, and then the `on_press` for the hstack should work.

**Comment by Fredemus** [comment]
Ah good to know, didn't know it was on purpose, I'll close this. Thanks!

**Comment by geom3trik** [comment]
Yeh it was changed to match the web so that press events don't go through self-directed views like overlays.
