### ISSUE TITLE
The image setting size is cropped

### ISSUE THREAD

**Issue by WZY1999428** [vizia/vizia#460]
Hello, the image setting size is cropped, instead of setting the image display size for scaling like the browser does. Is the function not perfect yet?

**Comment by geom3trik** [comment]
Hi, I'm not sure exactly what you're referring to here. The `background-size` property can be used to configure how an image fills its container. Is that what you mean?

**Comment by WZY1999428** [comment]
> Hi, I'm not sure exactly what you're referring to here. The `background-size` property can be used to configure how an image fills its container. Is that what you mean?

Thank you, that’s what I mean. I didn’t see this configuration document.
