### ISSUE TITLE
Moving back to upstream selectors?

### ISSUE THREAD

**Issue by nicoburns** [vizia/vizia#473]
Development on the Servo project has been picking up recently, and one of the things we're looking at is improving the maintenance of it's crates (including selectors which now lives in https://github.com/servo/stylo) and trying to merge back forks and pool development effort back into the original crates.

I am wondering:

- What changes has vizia made to selectors?
- What would it take to get vizia back on upstream selectors? (and would you be interested in doing this)?
- Would you be interested in helping to maintain upstream selectors?

**Comment by geom3trik** [comment]
Implemented in #514
