### ISSUE TITLE
Dropdowns should drop upwards if there's no space for them downwards

### ISSUE THREAD

**Issue by rhelmot** [vizia/vizia#48]
Barring winit suddenly supporting popup windows, we're going to need to prevent dropdowns from falling off the bottom of the screen and becoming unusable.

**Comment by geom3trik** [comment]
Should the dropdown be able to cover the button which triggers it? Or should it try to position itself where it doesn't cover the button?

**Comment by rhelmot** [comment]
Ideally it would a) position itself with top: 100% if possible, then position itself with bottom: 100% as a fallback, _then_ start covering the button if none of those are possible.

**Comment by rhelmot** [comment]
Can we push this for 0.1?

**Comment by geom3trik** [comment]
> Can we push this for 0.1?

Yep! Missed this one.
