### ISSUE TITLE
`rust-version = “1.79”` Is this really necessary right now?

### ISSUE THREAD

**Issue by Jhonfunk** [vizia/vizia#495]
1087b4a199584a8163aa4a718938a752875a2746

Is it too radical to lose support for windows 7 just for the convenience of a few syntax lines

**Comment by Greatness7** [comment]
You can still compile for Windows 7. You just have to setup the appropriate rustup tier 3 [target](https://github.com/rust-lang/rust/pull/118150).

(Note: I'm just a user/contributor and do not make decisions for the project, so the rest is just opinion.)

To answer the question: The Rust Organization, and even Microsoft themselves, have indeed deemed it too radical to continue to support Windows 7. It (Windows 7) has past both its official "end of life" date and "extended security updates" date, so anyone still using it should question that decision.

It will be very difficult, and frankly impractical, for anyone working on vizia to actually test for Windows 7. 

We could avoid the version constraint, but it'd just be pushing the decision down the road until the [next release](https://releases.rs/) when something appealing comes along. Considering vizia isn't even publicly released yet, and thus doesn't have legacy usage to worry about, now seems like the best time there ever will be to set a high minimum version.
