### ISSUE TITLE
Setting an ID value with #<name> seems to overwrite other values in css

### ISSUE THREAD

**Issue by mwallenfang** [vizia/vizia#63]
The minimal code showing what I think is a bug:
```rust
use vizia::*;

const STYLE: &str = r#"
#test {
    background-color: blue;
}

/* Simply make the knob itself smaller */
knob {
    width: 100px;
    height: 100px;
}

knob .track {
    background-color: #red;
}


"#;

#[derive(Lens)]
pub struct DummyData {
    data: f32
}

impl Model for DummyData {
    // Update the knob value
    fn event(&mut self, cx: &mut Context, event: &mut Event) {
        if let Some(pan_event) = event.message.downcast() {
            match pan_event {
                DummyEvents::Dummy(n) => {
                    self.data = *n;
                }
            }
        }
    }
}

enum DummyEvents {
    Dummy(f32)
}

fn main() {
    Application::new(WindowDescription::new()
                         .with_inner_size(150,150), move |cx| {
        DummyData{
            data: 0.5
        }.build(cx);
        cx.add_theme(STYLE);

        Knob::new(cx, 0.2, DummyData::data, true)
            .on_changing(|cx, val| cx.emit(DummyEvents::Dummy(val)));

    }).run();
}
```

This is just a simple UI containing a knob where the bar's colour is red. The css contains a field where the name starts with a `#` as if it was an element selected by an ID, thus it should just change nothing to my understanding.

The UI that I would then expect is this:
![grafik](https://user-images.githubusercontent.com/10572961/156900419-d0a2cfc7-28ec-4f35-ac18-21b45ddc631d.png)

But what actually happens is that all background-color values are overwritten with the value of `#test`, in this case `blue`:
![grafik](https://user-images.githubusercontent.com/10572961/156900433-9c07e4a3-f56c-420d-b4b3-6a8d43010156.png)

I managed to get the same problem with VStacks, HStacks and Labels.

**Comment by geom3trik** [comment]
Yep this is definitely a bug. So selecting by id is not currently supported, but as you correctly point out using it should not have any effect. Was there something specific you were trying to do when discovering this bug? Were you trying to set the color of some part of the knob?

**Comment by mwallenfang** [comment]
I initially basically had a knob and a Label that I wanted to have a specific background-color, so I gave it a class name and mixed up the css syntax for IDs and classes and stumbled upon this.

After removing stuff I boiled it down to the ID syntax breaking something so that it applied the background-color to a lot, if not all elements

**Comment by rhelmot** [comment]
I'm working on implementing id-selection right now.
