### ISSUE TITLE
Textboxes should position text to show cursor if text overflows box

### ISSUE THREAD

**Issue by rhelmot** [vizia/vizia#67]
Right now, you cant see what you're typing if you type text which is too long for a textbox. Let's make this work intuitively.

**Comment by geom3trik** [comment]
We could do this with a transform on the text rendering, though this might require the textbox to use custom drawing. Any thoughts on a possible implementation?

While we're on the subject of the textbox there's 2 other features I'd like to add:

- placeholder text when the textbox is empty
- an ellipsis (or custom character) at the end when the text overfl...

**Comment by rhelmot** [comment]
I think this is something we'll need another piece of state for, since you should be able to move the cursor around the text box without triggering text motion, unless you move it outside the bounds. The best interface for this is probably something like "move_position_into_bounds", which is called on cursor movement and updates the aforementioned state.

**Comment by geom3trik** [comment]
My thinking was that you could determine if the caret position is outside of the bounds of the textbox and then transform the text accordingly. So if the caret is inside the bounds then no transform happens. I'm not sureI understand what you mean by another piece of state and the `move_position_into_bounds` interface. What does this state track? Whether or not the caret is outside the textbox clip bounds?
