### ISSUE TITLE
30pt text as 2x DPI scaling renders badly

### ISSUE THREAD

**Issue by robbert-vdh** [vizia/vizia#81]
We discussed this on the Discord, but I'll also post it here so it doesn't get forgotten about. This is what happens when you render a label with a 30 point font size and the Noto Sans Thin font and 2x scaling (`application.with_scale_factor(WindowScalePolicy::ScaleFactor(2.0)` with #80):

![afbeelding](https://user-images.githubusercontent.com/748520/159001547-3f6878a1-97e0-4f6a-9e68-37c63633c164.png)

The other text, which is 15pt Noto Sans Light, looks fine. Let me know if you need more details for reproducing this.

**Comment by geom3trik** [comment]
Can you confirm if this is fixed by #84?

**Comment by robbert-vdh** [comment]
The text now renders correctly here at all scaling levels.
