### ISSUE TITLE
Interaction with the Textbox widget

### ISSUE THREAD

**Issue by robbert-vdh** [vizia/vizia#85]
Right now there's no way to programmatically control a text box widget from another widget holding one. It would be useful to be able to do things like focus the text box (as if the user clicked on it), move the caret around, and control the selection.

**Comment by geom3trik** [comment]
It's now currently possible to use events to focus the textbox and select all the text in the textbox. It's not yet possible to programatically change the caret position, other than to the end when selecting all of the text, but are these features sufficient for your use case?

**Comment by robbert-vdh** [comment]
I'll rebase again and check if everything's working correctly now (for this issue the other issues). Haven't had time to do so since I last tried it in mid-July and ran into the issues I posted about on the Discord around that time.

**Comment by geom3trik** [comment]
> I'll rebase again and check if everything's working correctly now (for this issue the other issues).

Thank you :) I think many of the issues were fixed by various commits that were never linked back to the issues.

**Comment by robbert-vdh** [comment]
Everything seems to be working great for my use case now, emiting `TextEvent::StartEdit` and `TextEvent::SelectAll` in an `.on_build()` callback on the text box.
