### ISSUE TITLE
Borders clip through ScrollViews

### ISSUE THREAD

**Issue by robbert-vdh** [vizia/vizia#89]
Running the following example: 

```rust
use vizia::*;

fn main() {
    Application::new(WindowDescription::new().with_title("Basic"), |cx| {
        ScrollView::new(cx, 0.0, 0.0, false, true, |cx| {
            for i in 0..100 {
                Label::new(cx, &format!("Label {i}"))
                    .border_color(Color::black())
                    .border_width(Pixels(1.0));
            }
        })
        .width(Percentage(100.0))
        .height(Pixels(100.0));
    })
    .run();
}
```

Causes this to happen:

https://user-images.githubusercontent.com/748520/160296583-09c35c42-1e33-471f-9bd0-10747445c52e.mp4

These borders should not be drawn at all. I've found some other issues with `ScrollView` involving DPI scaling, I'll create another issue for those.

**Comment by robbert-vdh** [comment]
These lines are likely (supposed to be) part of the anti-aliasing. Commit #89 works around this on 1.0x scaling, but the issue still exists when using any other scaling multiplier.

**Comment by geom3trik** [comment]
I have tested this again on a monitor with 1.25 scale factor and I am unable to reproduce the issue. I'm hoping one of the commits since this issue was raised has fixed the problem but I wouldn't be able to tell you which one at the moment. When you get a chance, could you test this again to confirm if the issue is resolved for you? Here is the updated example for the updated API:
```rust
use vizia::prelude::*;

fn main() {
    Application::new(|cx| {
        ScrollView::new(cx, 0.0, 0.0, false, true, |cx| {
            for i in 0..100 {
                Label::new(cx, &format!("Label {i}"))
                    .border_color(Color::black())
                    .border_width(Pixels(1.0));
            }
        })
        .width(Percentage(100.0))
        .height(Pixels(100.0));
    })
    .run();
}
```

**Comment by robbert-vdh** [comment]
I think this indeed works correctly now!
